import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Blur } from "@/app/components/ui/blur";
import { SideBar } from "../components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative flex p-2 h-screen  overflow-y-hidden">
          <SideBar />
          <main className="w-full">{children}</main>
          <Blur className="h-[400px] w-[400px] top-2/5 left-1/10" />
          <Blur className="h-[400px] w-[400px] top-1/5 left-7/10" />
        </div>
      </body>
    </html>
  );
}
